AllCops:
  TargetRubyVersion: 2.3.3
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 27

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
